sudo: required
services:
 - docker

before_install:
 - docker build -t coolshaddy/docker-react -f Dockerfile.dev .

script:
 - docker run coolshaddy/docker-react npm run test -- --coverage --watchAll=false

deploy:
 provider: elasticbeanstalk
 edge: true
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key: "$AWS_SECRET_KEY"
 region: "eu-west-1"
 app: "myapp"
 env: "Myapp-env"
 bucket: "elasticbeanstalk-eu-west-1-955387369960"
 bucket_path: "myapp"
 on:
  branch: master

