sudo: required
services:
 - docker

before_install:
 - docker build -t coolshaddy/docker-react -f Dockerfile.dev .

script:
 - docker run coolshaddy/docker-react npm run test -- --coverage --watchAll=false

deploy:
 provider: elasticbeanstalk
 edge: true
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key: "$AWS_SECRET_KEY"
 region: "us-east-1"
 app: "demo"
 env: "Demo-env"
 bucket: "elasticbeanstalk-us-east-1-349382015220"
 bucket_path: "demo"
 on:
  branch: master
 
